name: FluffysConstruct
author: NCBPFluffyBear
description: A Spigot port of the popular mod Tinkers' Construct
main: io.ncbpfluffybear.fluffysconstruct.FCPlugin
version: ${project.version}
api-version: 1.16

commands:
  fluffysconstruct:
    aliases: [fc]
    permission: op
    description: FC super command